name: Generate linux packages

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Build DEB package
        uses: DevChall-by-SDCY-and-VXM/debian-buildpackage-template@v0.0.10
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: built-deb-files.zip
